spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/roouty?characterEncoding=UTF-8&serverTimezone=UTC
    username: test
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

logging:
  level:
    root: INFO
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG
